receivers:
  otlp:
    protocols:
      http: 
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

exporters:
  otlphttp:
    endpoint: https://literate-space-tribble-pjx97w99vqwjhrq75-14318.app.github.dev/  
  logging:
    loglevel: info

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, logging]
